"""empty message

Revision ID: 9f7fa13477af
Revises: 11d7a4a8ac10
Create Date: 2021-03-25 21:08:41.849913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f7fa13477af'
down_revision = '11d7a4a8ac10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('admin_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'group', 'user', ['admin_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'group', type_='foreignkey')
    op.drop_column('group', 'admin_id')
    # ### end Alembic commands ###
