"""initial migrate

Revision ID: fd096d590228
Revises: 
Create Date: 2021-02-28 16:14:55.648597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd096d590228'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(length=25), nullable=True),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('registered', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nickname')
    )
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_table('groups_subscribers',
    sa.Column('primary_key', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('primary_key')
    )
    op.create_index(op.f('ix_groups_subscribers_group_id'), 'groups_subscribers', ['group_id'], unique=False)
    op.create_index(op.f('ix_groups_subscribers_user_id'), 'groups_subscribers', ['user_id'], unique=False)
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('picture', sa.LargeBinary(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('is_reply', sa.Boolean(), nullable=True),
    sa.Column('reply_to', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('posts_likes',
    sa.Column('primary_key', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('primary_key')
    )
    op.create_index(op.f('ix_posts_likes_post_id'), 'posts_likes', ['post_id'], unique=False)
    op.create_index(op.f('ix_posts_likes_user_id'), 'posts_likes', ['user_id'], unique=False)
    op.create_table('comments_likes',
    sa.Column('primary_key', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['comment.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('primary_key')
    )
    op.create_index(op.f('ix_comments_likes_comment_id'), 'comments_likes', ['comment_id'], unique=False)
    op.create_index(op.f('ix_comments_likes_user_id'), 'comments_likes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comments_likes_user_id'), table_name='comments_likes')
    op.drop_index(op.f('ix_comments_likes_comment_id'), table_name='comments_likes')
    op.drop_table('comments_likes')
    op.drop_index(op.f('ix_posts_likes_user_id'), table_name='posts_likes')
    op.drop_index(op.f('ix_posts_likes_post_id'), table_name='posts_likes')
    op.drop_table('posts_likes')
    op.drop_table('comment')
    op.drop_table('post')
    op.drop_index(op.f('ix_groups_subscribers_user_id'), table_name='groups_subscribers')
    op.drop_index(op.f('ix_groups_subscribers_group_id'), table_name='groups_subscribers')
    op.drop_table('groups_subscribers')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_table('user')
    op.drop_table('group')
    # ### end Alembic commands ###
